package com.zhengjianbin.model;

import com.zhengjianbin.model.base.BaseJfinalTest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JfinalTest extends BaseJfinalTest<JfinalTest> {
	public static final JfinalTest dao = new JfinalTest().dao();
}
